#
# Makefile for the Solomon Systech SSD20xx touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_SSL_SSD20xx) += ssd20xx_mx25v100.o ssd20xx_upgrade.o ssl_ssd20xx.o
