#
# Makefile for the Solomon Systech SSD20xx touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_SSL_SSD20xx_DRIVER) += ssl_ssd20xx.o
obj-$(CONFIG_TOUCHSCREEN_SSL_SSD20xx_UPDATE) += ssd20xx_upgrade.o 
obj-$(CONFIG_TOUCHSCREEN_SSD2098) += ssd20xx_mx25v100.o
